### ISSUE TITLE
Top Creators - sortowanie w kolejności - by_name->by_count

### ISSUE THREAD

**Issue by mutipg** [openstreetmap-polska/aed_backup#4]
Nie potrafię utworzyć odpowiedniego kodu ale może dla Was to nie będzie nic trudnego :)

Czy można dodać dodatkowy klucz sortowania w tabeli Top Creators tak, ażeby najpierw posortować userów po nazwie a dopiero później po ilości dodanych AED? Pewnie gdzieś tutaj trzeba dodać odpowiedni warunek: https://github.com/openstreetmap-polska/aed_backup/blob/master/report.py#L119

Teraz przy równej liczbie AED pozycje użytkowników w raporcie są zmienne przy generowaniu nowego raportu - np. tutaj:
https://github.com/openstreetmap-polska/aed_backup/commit/ac63080720a25bcb1122866f70a840f4b3b61066#diff-01e6d9ffed056a02cae8d8a0ec5d476a64d017bf85c0d5a94bb23ca21f33f5aaL13

![image](https://github.com/openstreetmap-polska/aed_backup/assets/10333015/b71837d0-3ced-409d-b6ee-4b4d4a929295)

**Comment by mutipg** [comment]
@praszuk, dzięki za update https://github.com/openstreetmap-polska/aed_backup/commit/d37e10e041313adcba12dae78cdd3cf23dff3dff - chyba o to mi chodziło :)

**Comment by praszuk** [comment]
@mutipg nie zdążyłem skomentować i zamknąć issue :sweat_smile: Daj znać gdyby nadal nie działało jak trzeba.
