### ISSUE TITLE
Top Creators nie zlicza poprawnie, gdy AED zostanie usunięte z OSM

### ISSUE THREAD

**Issue by mutipg** [openstreetmap-polska/aed_backup#5]
Być może jest to działanie prawidłowe ale wydaje mi się, że jeśli dodane przez kogoś AED zostanie usunięte z mapy OSM, to licznik dodanych AED przez użytkownika również powinien zostać zaktualizowany in minus. Ostatnio źle zinterpretowałem artykuł i dodałem błędnie 12 AED, które po ok. 7 godzinach usunąłem.

Po dodaniu 12 AED przeze mnie w TopCreators jest wzrost licznika z 607 do 619
https://github.com/openstreetmap-polska/aed_backup/commit/e41dc78dbf4bc311537c11b22ae922159772f42f?diff=unified&w=0#diff-01e6d9ffed056a02cae8d8a0ec5d476a64d017bf85c0d5a94bb23ca21f33f5aaL17
![image](https://github.com/openstreetmap-polska/aed_backup/assets/10333015/fe2459af-e7d3-49a4-bdb5-002bb20e1f5f)

Po usunięciu 12 błędnych AED stan licznika jest bez zmian i nadal mam 619 AED na swoim koncie.
https://github.com/openstreetmap-polska/aed_backup/blob/10140e5a9bb218d33a5284b609bf1c534abd1b39/README.MD?plain=1#L17
| # | User | Created |
| ------------- | ------------- | ------------- |
| 2 | [Marek-M](<https://www.openstreetmap.org/user/Marek-M>) | 619 |

**Comment by praszuk** [comment]
@mutipg Tak, to było/jest celowe, żeby liczyć same utworzenia bez względu na to, czy później zostają zmodyfikowane/usunięte.

**Comment by mutipg** [comment]
Dzięki za odpowiedź. Rozumiem założenie :) Mam nadzieję, że sytuacje z błędnym dodawaniem AED są marginalne ale chyba ze 3 razy mi się coś takiego przytrafiło :)

Możemy zatem zamknąć wątek co niniejszym czynię.
