### ISSUE TITLE
Tytuły commits na GitHub bez informacji o ilości zmian

### ISSUE THREAD

**Issue by mutipg** [openstreetmap-polska/aed_backup#6]
Od 7 kwietnia 2024r. tytuły commitów na GitHub zmieniły format - wcześniej była podawana informacja o ilości zmian AED  np.:
[**AED update (C: 0, M: 1, D: 2)**]
a od 7 kwietnia jest po prostu:
[**Update AED**]

Czy jest możliwość przywrócenia wcześniejszego formatu tytułów, bo obecnie nie niosą żadnej informacji?

![image](https://github.com/openstreetmap-polska/aed_backup/assets/10333015/43eb6ca2-86f1-4df6-b5ef-77be29b45254)

**Comment by Zaczero** [comment]
Poprawione :+1:
